name: Check Target Directory

description: Action to checkout repository, check if target directory exists, and set outputs.

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check if target directory exists
      shell: bash
      run: |
        if [ ! -d "${{ github.workspace }}/${{ inputs.directory }}" ]; then
          echo "Target directory not found: ${{ github.workspace }}/${{ inputs.directory }}"
          exit 1
        fi

    - name: Set outputs
      shell: bash
      id: set_outputs
      run: |
        echo "Setting constants."
        
outputs:
  TARGET_DIRECTORY: 
    description: 'The target directory.'
    value: ${{ inputs.directory }}

inputs:
  directory:
    description: 'The target directory to check.'
    required: true
