name: Sync

on:
  push:
    branches: [main, dev/main]
    paths:
      - .github/labels
      - .github/rules
  schedule:
    - cron: '0 0 * * 0'

jobs:
  sync-labels:
    permissions:
      issues: write
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn add -D @azu/github-label-setup
      - name: Run github-label-setup
        run: yarn github-label-setup --token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels/labels.json
  
  set-branch-protection:
  # https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read branch protection rules
        id: read_rules
        run: |
          rules=$(jq -c . .github/rules/personal-branch-protection.json)
          echo "rules=$rules" >> $GITHUB_ENV

      - name: Set branch protection rules
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          RULES: ${{ env.rules }}
        run: |
          echo $RULES | jq . # This line is optional, it helps in debugging by printing the rules
          curl -X PUT -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d "$RULES"